//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInfoo
    {
        public int UserID { get; set; }
        [Required]
       // [Display(Name = "Enter User Name")]
        public string UserName { get; set; }
        [Required]
     //   [Display(Name = "example@test.com")]
        public string Email { get; set; }
        [Required]
        [DataType("Password")]
     //   [Display(Name = "Enter Your Password")]
        public string Password { get; set; }
        [Required]
        [DataType("Password")]
     //   [Display(Name = "ReEnter Your Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }


    }
}
